<template>
  <div>
    <v-autocomplete
      v-model="countrySelected"
      :items="countries"
      item-text="state"
      item-value="code"
      label="Select country"
      :hint="`${countrySelected.state}, ${countrySelected.code}`"
      return-object
    ></v-autocomplete>
  </div>
</template>

<script>
export default {
  data() {
    return {
      countrySelected: { state: "", code: "" },
      countries: [
        { state: "Afghanistan", code: "AF" },
        { state: "Åland Islands", code: "AX" },
        { state: "Albania", code: "AL" },
        { state: "Algeria", code: "DZ" },
        { state: "American Samoa", code: "AS" },
        { state: "AndorrA", code: "AD" },
        { state: "Angola", code: "AO" },
        { state: "Anguilla", code: "AI" },
        { state: "Antarctica", code: "AQ" },
        { state: "Antigua and Barbuda", code: "AG" },
        { state: "Argentina", code: "AR" },
        { state: "Armenia", code: "AM" },
        { state: "Aruba", code: "AW" },
        { state: "Australia", code: "AU" },
        { state: "Austria", code: "AT" },
        { state: "Azerbaijan", code: "AZ" },
        { state: "Bahamas", code: "BS" },
        { state: "Bahrain", code: "BH" },
        { state: "Bangladesh", code: "BD" },
        { state: "Barbados", code: "BB" },
        { state: "Belarus", code: "BY" },
        { state: "Belgium", code: "BE" },
        { state: "Belize", code: "BZ" },
        { state: "Benin", code: "BJ" },
        { state: "Bermuda", code: "BM" },
        { state: "Bhutan", code: "BT" },
        { state: "Bolivia", code: "BO" },
        { state: "Bosnia and Herzegovina", code: "BA" },
        { state: "Botswana", code: "BW" },
        { state: "Bouvet Island", code: "BV" },
        { state: "Brazil", code: "BR" },
        { state: "British Indian Ocean Territory", code: "IO" },
        { state: "Brunei Darussalam", code: "BN" },
        { state: "Bulgaria", code: "BG" },
        { state: "Burkina Faso", code: "BF" },
        { state: "Burundi", code: "BI" },
        { state: "Cambodia", code: "KH" },
        { state: "Cameroon", code: "CM" },
        { state: "Canada", code: "CA" },
        { state: "Cape Verde", code: "CV" },
        { state: "Cayman Islands", code: "KY" },
        { state: "Central African Republic", code: "CF" },
        { state: "Chad", code: "TD" },
        { state: "Chile", code: "CL" },
        { state: "China", code: "CN" },
        { state: "Christmas Island", code: "CX" },
        { state: "Cocos (Keeling) Islands", code: "CC" },
        { state: "Colombia", code: "CO" },
        { state: "Comoros", code: "KM" },
        { state: "Congo", code: "CG" },
        { state: "Congo, The Democratic Republic of the", code: "CD" },
        { state: "Cook Islands", code: "CK" },
        { state: "Costa Rica", code: "CR" },
        { state: "Cote D'Ivoire", code: "CI" },
        { state: "Croatia", code: "HR" },
        { state: "Cuba", code: "CU" },
        { state: "Cyprus", code: "CY" },
        { state: "Czech Republic", code: "CZ" },
        { state: "Denmark", code: "DK" },
        { state: "Djibouti", code: "DJ" },
        { state: "Dominica", code: "DM" },
        { state: "Dominican Republic", code: "DO" },
        { state: "Ecuador", code: "EC" },
        { state: "Egypt", code: "EG" },
        { state: "El Salvador", code: "SV" },
        { state: "Equatorial Guinea", code: "GQ" },
        { state: "Eritrea", code: "ER" },
        { state: "Estonia", code: "EE" },
        { state: "Ethiopia", code: "ET" },
        { state: "Falkland Islands (Malvinas)", code: "FK" },
        { state: "Faroe Islands", code: "FO" },
        { state: "Fiji", code: "FJ" },
        { state: "Finland", code: "FI" },
        { state: "France", code: "FR" },
        { state: "French Guiana", code: "GF" },
        { state: "French Polynesia", code: "PF" },
        { state: "French Southern Territories", code: "TF" },
        { state: "Gabon", code: "GA" },
        { state: "Gambia", code: "GM" },
        { state: "Georgia", code: "GE" },
        { state: "Germany", code: "DE" },
        { state: "Ghana", code: "GH" },
        { state: "Gibraltar", code: "GI" },
        { state: "Greece", code: "GR" },
        { state: "Greenland", code: "GL" },
        { state: "Grenada", code: "GD" },
        { state: "Guadeloupe", code: "GP" },
        { state: "Guam", code: "GU" },
        { state: "Guatemala", code: "GT" },
        { state: "Guernsey", code: "GG" },
        { state: "Guinea", code: "GN" },
        { state: "Guinea-Bissau", code: "GW" },
        { state: "Guyana", code: "GY" },
        { state: "Haiti", code: "HT" },
        { state: "Heard Island and Mcdonald Islands", code: "HM" },
        { state: "Holy See (Vatican City State)", code: "VA" },
        { state: "Honduras", code: "HN" },
        { state: "Hong Kong", code: "HK" },
        { state: "Hungary", code: "HU" },
        { state: "Iceland", code: "IS" },
        { state: "India", code: "IN" },
        { state: "Indonesia", code: "ID" },
        { state: "Iran, Islamic Republic Of", code: "IR" },
        { state: "Iraq", code: "IQ" },
        { state: "Ireland", code: "IE" },
        { state: "Isle of Man", code: "IM" },
        { state: "Israel", code: "IL" },
        { state: "Italy", code: "IT" },
        { state: "Jamaica", code: "JM" },
        { state: "Japan", code: "JP" },
        { state: "Jersey", code: "JE" },
        { state: "Jordan", code: "JO" },
        { state: "Kazakhstan", code: "KZ" },
        { state: "Kenya", code: "KE" },
        { state: "Kiribati", code: "KI" },
        { state: "Korea, Democratic People'S Republic of", code: "KP" },
        { state: "Korea, Republic of", code: "KR" },
        { state: "Kuwait", code: "KW" },
        { state: "Kyrgyzstan", code: "KG" },
        { state: "Lao People'S Democratic Republic", code: "LA" },
        { state: "Latvia", code: "LV" },
        { state: "Lebanon", code: "LB" },
        { state: "Lesotho", code: "LS" },
        { state: "Liberia", code: "LR" },
        { state: "Libyan Arab Jamahiriya", code: "LY" },
        { state: "Liechtenstein", code: "LI" },
        { state: "Lithuania", code: "LT" },
        { state: "Luxembourg", code: "LU" },
        { state: "Macao", code: "MO" },
        { state: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
        { state: "Madagascar", code: "MG" },
        { state: "Malawi", code: "MW" },
        { state: "Malaysia", code: "MY" },
        { state: "Maldives", code: "MV" },
        { state: "Mali", code: "ML" },
        { state: "Malta", code: "MT" },
        { state: "Marshall Islands", code: "MH" },
        { state: "Martinique", code: "MQ" },
        { state: "Mauritania", code: "MR" },
        { state: "Mauritius", code: "MU" },
        { state: "Mayotte", code: "YT" },
        { state: "Mexico", code: "MX" },
        { state: "Micronesia, Federated States of", code: "FM" },
        { state: "Moldova, Republic of", code: "MD" },
        { state: "Monaco", code: "MC" },
        { state: "Mongolia", code: "MN" },
        { state: "Montserrat", code: "MS" },
        { state: "Morocco", code: "MA" },
        { state: "Mozambique", code: "MZ" },
        { state: "Myanmar", code: "MM" },
        { state: "Namibia", code: "NA" },
        { state: "Nauru", code: "NR" },
        { state: "Nepal", code: "NP" },
        { state: "Netherlands", code: "NL" },
        { state: "Netherlands Antilles", code: "AN" },
        { state: "New Caledonia", code: "NC" },
        { state: "New Zealand", code: "NZ" },
        { state: "Nicaragua", code: "NI" },
        { state: "Niger", code: "NE" },
        { state: "Nigeria", code: "NG" },
        { state: "Niue", code: "NU" },
        { state: "Norfolk Island", code: "NF" },
        { state: "Northern Mariana Islands", code: "MP" },
        { state: "Norway", code: "NO" },
        { state: "Oman", code: "OM" },
        { state: "Pakistan", code: "PK" },
        { state: "Palau", code: "PW" },
        { state: "Palestinian Territory, Occupied", code: "PS" },
        { state: "Panama", code: "PA" },
        { state: "Papua New Guinea", code: "PG" },
        { state: "Paraguay", code: "PY" },
        { state: "Peru", code: "PE" },
        { state: "Philippines", code: "PH" },
        { state: "Pitcairn", code: "PN" },
        { state: "Poland", code: "PL" },
        { state: "Portugal", code: "PT" },
        { state: "Puerto Rico", code: "PR" },
        { state: "Qatar", code: "QA" },
        { state: "Reunion", code: "RE" },
        { state: "Romania", code: "RO" },
        { state: "Russian Federation", code: "RU" },
        { state: "RWANDA", code: "RW" },
        { state: "Saint Helena", code: "SH" },
        { state: "Saint Kitts and Nevis", code: "KN" },
        { state: "Saint Lucia", code: "LC" },
        { state: "Saint Pierre and Miquelon", code: "PM" },
        { state: "Saint Vincent and the Grenadines", code: "VC" },
        { state: "Samoa", code: "WS" },
        { state: "San Marino", code: "SM" },
        { state: "Sao Tome and Principe", code: "ST" },
        { state: "Saudi Arabia", code: "SA" },
        { state: "Senegal", code: "SN" },
        { state: "Serbia and Montenegro", code: "CS" },
        { state: "Seychelles", code: "SC" },
        { state: "Sierra Leone", code: "SL" },
        { state: "Singapore", code: "SG" },
        { state: "Slovakia", code: "SK" },
        { state: "Slovenia", code: "SI" },
        { state: "Solomon Islands", code: "SB" },
        { state: "Somalia", code: "SO" },
        { state: "South Africa", code: "ZA" },
        { state: "South Georgia and the South Sandwich Islands", code: "GS" },
        { state: "Spain", code: "ES" },
        { state: "Sri Lanka", code: "LK" },
        { state: "Sudan", code: "SD" },
        { state: "Suriname", code: "SR" },
        { state: "Svalbard and Jan Mayen", code: "SJ" },
        { state: "Swaziland", code: "SZ" },
        { state: "Sweden", code: "SE" },
        { state: "Switzerland", code: "CH" },
        { state: "Syrian Arab Republic", code: "SY" },
        { state: "Taiwan, Province of China", code: "TW" },
        { state: "Tajikistan", code: "TJ" },
        { state: "Tanzania, United Republic of", code: "TZ" },
        { state: "Thailand", code: "TH" },
        { state: "Timor-Leste", code: "TL" },
        { state: "Togo", code: "TG" },
        { state: "Tokelau", code: "TK" },
        { state: "Tonga", code: "TO" },
        { state: "Trinidad and Tobago", code: "TT" },
        { state: "Tunisia", code: "TN" },
        { state: "Turkey", code: "TR" },
        { state: "Turkmenistan", code: "TM" },
        { state: "Turks and Caicos Islands", code: "TC" },
        { state: "Tuvalu", code: "TV" },
        { state: "Uganda", code: "UG" },
        { state: "Ukraine", code: "UA" },
        { state: "United Arab Emirates", code: "AE" },
        { state: "United Kingdom", code: "GB" },
        { state: "United States", code: "US" },
        { state: "United States Minor Outlying Islands", code: "UM" },
        { state: "Uruguay", code: "UY" },
        { state: "Uzbekistan", code: "UZ" },
        { state: "Vanuatu", code: "VU" },
        { state: "Venezuela", code: "VE" },
        { state: "Viet Nam", code: "VN" },
        { state: "Virgin Islands, British", code: "VG" },
        { state: "Virgin Islands, U.S.", code: "VI" },
        { state: "Wallis and Futuna", code: "WF" },
        { state: "Western Sahara", code: "EH" },
        { state: "Yemen", code: "YE" },
        { state: "Zambia", code: "ZM" },
        { state: "Zimbabwe", code: "ZW" }
      ]
    };
  }
};
</script>
